### ISSUE TITLE
How to match sample names from microbiome and metabolomics?

### ISSUE THREAD

**Issue by zhanxw** [qpmnguyen/infant_metabolome_robust_variation_microbiome#1]
Thanks for your work and I enjoy your publication "“Associations between the gut microbiome and metabolome in early life”.

Can you offer help on linking the names from microbiome and metabolomics?

When I examined the microbiome data (https://www.ncbi.nlm.nih.gov/bioproject?LinkName=biosample_bioproject&from_uid=20178900) and metabolomics data (https://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&StudyID=ST001813&StudyType=NMR&ResultType=5), I found that sample names do not match. For example, the microbiome sample IDs look like `nhbcs_0918800192000426_Bv4v5` (https://www.ncbi.nlm.nih.gov/sra/SRX10203119[accn]), but the metabolomics sample IDs are like `S_101_1Y` (https://www.metabolomicsworkbench.org/data/subject_fetch.php?STUDY_ID=ST001813&STUDY_TYPE=NMR&RESULT_TYPE=5).
 
Thanks.

**Comment by qpmnguyen** [comment]
Hi!

Thank you for writing to me! I'll get back to you about this matching procedure. Can you also send an email? That way I can let my advisor (the senior author) know as well. You can reach us at Anne.G.Hoen@dartmouth.edu and Quang.P.Nguyen.GR@dartmouth.edu.  

I'll close the issue for now.
